import * as gempa from "./gempa.mjs";
import * as cuaca from "./cuaca.mjs";
import * as berita from "./berita.mjs";
import * as wilayah from "./wilayah.mjs";
import * as kodepos from "./kodepos.mjs";
import * as kurs from "./kurs.mjs";
import * as saham from "./saham.mjs";
import * as data from "./data.mjs";
import * as bps from "./bps.mjs";
import * as sosial from "./sosial.mjs";
import * as udara from "./udara.mjs";
import * as ihsg from "./ihsg.mjs";
import * as sholat from "./sholat.mjs";
import * as quran from "./quran.mjs";
import * as hijriah from "./hijriah.mjs";
import * as pesawat from "./pesawat.mjs";
import * as doa from "./doa.mjs";
import * as wiki from "./wiki.mjs";
import * as maritim from "./maritim.mjs";
import * as musik from "./musik.mjs";
import * as bbm from "./bbm.mjs";

export const CHANNELS = { gempa, cuaca, berita, wilayah, kodepos, kurs, saham, ihsg, sholat, quran, hijriah, pesawat, doa, wiki, maritim, musik, bbm, data, bps, sosial, udara };
